alternate: Trafooder
author: Trafooder
title: Trafooder's Blog
menu:
  Home: /
  Archives: /archives/
avatar:
  url: /assets/logo.svg
  rounded: true
  opacity: 1
image_list:
  - /assets/404.png
  - /assets/algolia_logo.svg
  - /assets/apple-touch-icon.png
  - /assets/favicon.ico
  - /assets/logo.svg
  - /assets/search.png
loader:
  start: true
